services:
  railways-timetable-telegram-bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: railways-timetable-telegram-bot
    restart: unless-stopped
    env_file:
      - .env  # Load all variables from .env file
    depends_on:
      - railways-timetable-backend

  railways-timetable-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: railways-timetable-backend
    restart: unless-stopped
    env_file:
      - .env  # Load all variables from .env file
    ports:
      - "8080:8080"
