[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "*"
envy = "*"
env_logger = "*"
strsim = "0.11.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
actix-web = { version = "4" }
actix-cors = "0.7"
awc = { version = "3.6", features = ["rustls"] }
parking_lot = "0.12.3"
log = "0.4.27"